title: Astro Club IITK
description: A comprehensive guide to Astronomy Club IITK
theme: just-the-docs

url: https://astroclubiitk.github.io/wiki

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: '/assets/images/favicon.ico'

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
